name: Build cursor

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-fc42:
    name: Build cursor rpm for fedora 42
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Get current date
        run: |
          RESPONSE=$(curl -s 'https://cursor.com/api/download?platform=linux-x64&releaseTrack=stable')
          CURSOR_VERSION=$(echo $RESPONSE | jq -r '.version')
          echo "CURRENT_DATE=$(date --rfc-3339=date) $(date +%R)" >> ${GITHUB_ENV}
          echo "TAG_NAME=$CURSOR_VERSION" >> ${GITHUB_ENV}
          echo "RELEASE_NAME=cursor-$CURSOR_VERSION" >> ${GITHUB_ENV}

      - name: Check if version already exists
        id: release_exists
        run: |
          RELEASE_ID="${{ env.TAG_NAME }}"
          set +e
          RELEASE_RESPONSE=$(gh release view $RELEASE_ID --json tagName --jq .tagName 2>&1)
          if [ "$RELEASE_RESPONSE" = "$RELEASE_ID" ]; then
            echo "RELEASE_EXISTS=YES" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_EXISTS=NO" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        if: ${{ steps.release_exists.outputs.RELEASE_EXISTS == 'NO' }}
        run: |
          docker build -t cursor-fedora42:latest .

      - name: Build cursor rpm
        if: ${{ steps.release_exists.outputs.RELEASE_EXISTS == 'NO' }}
        run: |
          docker run -v "$(pwd)/out:/root/rpmbuild/RPMS/x86_64" cursor-fedora42:latest

      - uses: ncipollo/release-action@v1
        if: ${{ steps.release_exists.outputs.RELEASE_EXISTS == 'NO' }}
        with:
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          makeLatest: True
          artifacts: "out/*.rpm"
